name: Terraform
on:
  pull_request:
    branches: 
      - master
    types:
      - closed
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: terraform
        run: | 
         cd ~/localrepo
         export no_proxy=192.168.11.0/24
         git pull origin master
         cp main.tf ../execute_terraform
         cd ../execute_terraform
         terraform init
         terraform plan
         echo "terraform apply -auto-approve"
         echo "Done!"
