name: Action Sample

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  echo:
    runs-on: self-hosted
    steps:
      - name: terraform
        run: | 
         cd ~/localrepo
         git pull origin master
         terraform init 
         teraform apply
         echo "Done!"
