name: Action Sample

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: | 
         echo "Hello GitHub Actions!"
         echo "Commit test"
